---
- hosts: localhost
  gather_facts: false
  become: true
  vars:
    user: mh
  tasks:
    - name: Install packages
      package:
        name: '{{ pkgs }}'
      tags: package
      vars:
        pkgs:
          # Utility
          - bat
          - bind
          - exa
          - htop
          - inetutils
          - which
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          # Development tools
          - base-devel
          - go
          - rustup
          # Desktop environment
          - lightdm
          - lightdm-webkit2-greeter
          - lightdm-webkit-theme-litarvan
          - xorg-server
          # Applications
          - alacritty
          - chromium
          - podman

    - name: Set greeter
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: 'Seat:*'
        option: greeter-session
        value: lightdm-webkit2-greeter

    - name: Configure greeter theme
      ini_file:
        path: /etc/lightdm/lightdm-webkit2-greeter.conf
        section: greeter
        option: webkit_theme
        value: litarvan

    - name: Enable lightdm
      service:
        name: lightdm
        enabled: true

    - name: Set up podman for rootless mode
      lineinfile:
        path: '/etc/sub{{ item }}'
        line: '{{ user }}:10000:65536'
        regexp: '^{{ user }}:'
        create: true
        owner: root
        group: root
        mode: '0644'
      loop: [uid, gid]

    - name: Configure registries
      copy:
        dest: /etc/containers/registries.conf
        content: |
          [[registry]]
          location = "docker.io"
          [[registry.mirror]]
          location = "registry.mhnet.dev"
