---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Install packages
      package:
        name: '{{ pkgs }}'
      vars:
        pkgs:
          # Utility
          - bat
          - bind
          - exa
          - htop
          - inetutils
          - which
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          # Development tools
          - base-devel
          - go
          - rustup
          # Desktop environment
          - konsole
          - lightdm
          - lightdm-webkit2-greeter
          - lightdm-webkit-theme-litarvan
          - plasma-desktop
          - xorg-server

    - name: Set greeter
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: 'Seat:*'
        option: greeter-session
        value: lightdm-webkit2-greeter

    - name: Configure greeter theme
      ini_file:
        path: /etc/lightdm/lightdm-webkit2-greeter.conf
        section: greeter
        option: webkit_theme
        value: litarvan

    - name: Enable lightdm
      service:
        name: lightdm
        enabled: true
