---
- hosts: localhost
  gather_facts: false
  become: true
  vars:
    user: mh
  roles:
    - name: arch
      tags: [arch]
    - name: base
      tags: [base]
    - name: lenovo
      tgas: [lenovo]
    - name: podman
      tags: [podman]
