---
- name: Install packages
  ansible.builtin.package:
    name: "{{ pkgs }}"
  tags: package
  vars:
    pkgs:
      # Development tools
      - base-devel
      # Desktop environment
      - alacritty
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
      - lightdm
      - lightdm-webkit-theme-litarvan
      - lightdm-webkit2-greeter
      - xorg-server

- name: Set greeter
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: greeter-session
    value: lightdm-webkit2-greeter

- name: Configure greeter theme
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    section: greeter
    option: webkit_theme
    value: litarvan

- name: Enable lightdm
  ansible.builtin.service:
    name: lightdm
    enabled: true
