---
- name: Install packages
  ansible.builtin.package:
    name: "{{ pkgs }}"
  tags: package
  vars:
    pkgs:
      # Development tools
      - base-devel
      # Desktop environment
      - alacritty
      - i3-gaps
      - i3blocks
      - i3lock
      - i3status
      - lightdm
      - lightdm-webkit-theme-litarvan
      - lightdm-webkit2-greeter
      - xorg-server

      # Bluetooth
      - bluez
      - bluez-utils

- name: Configure DNS resolution
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Set greeter
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: greeter-session
    value: lightdm-webkit2-greeter

- name: Configure greeter theme
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    section: greeter
    option: webkit_theme
    value: litarvan

- name: Enable lightdm
  ansible.builtin.service:
    name: lightdm
    enabled: true

- name: Enable Bluetooth on start
  ansible.builtin.ini_file:
    path: /etc/bluetooth/main.conf
    section: Policy
    option: AutoEnable
    value: "true"

- name: Install hotplug_monitor
  ansible.builtin.template:
    src: templates/hotplug_monitor.j2
    dest: "/home/{{ user }}/bin/hotplug_monitor"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Install hotplug_monitor udev rule
  ansible.builtin.template:
    src: templates/dock-udev.rules.j2
    dest: /etc/udev/rules.d/80-dock.rules
    owner: root
    group: root
    mode: "0644"

- name: Fix screen setup on boot
  ansible.builtin.template:
    src: templates/xorg-resolution-fix.conf.j2
    dest: /etc/X11/xorg.conf.d/52-resolution-fix.conf
    owner: root
    group: root
    mode: "0644"
