---
- name: Install packages
  ansible.builtin.package:
    name: "{{ pkgs }}"
  tags: package
  vars:
    pkgs:
      # Utility
      - bat
      - bind
      - exa
      - htop
      - inetutils
      - which
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      # Development tools
      - base-devel
      # Desktop environment
      - lightdm
      - lightdm-webkit2-greeter
      - lightdm-webkit-theme-litarvan
      - xorg-server
      - alacritty

- name: Set greeter
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: greeter-session
    value: lightdm-webkit2-greeter

- name: Configure greeter theme
  ansible.builtin.ini_file:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    section: greeter
    option: webkit_theme
    value: litarvan

- name: Enable lightdm
  ansible.builtin.service:
    name: lightdm
    enabled: true
