---
- name: Install packages
  ansible.builtin.package:
    name: "{{ pkgs }}"
  tags: package
  vars:
    pkgs:
      # Utility
      - bat
      - bind
      - exa
      - git
      - htop
      - inetutils
      - openssh
      - tmux
      - which
      - zsh-autosuggestions
      - zsh-syntax-highlighting

- name: Ensure some directories exists
  ansible.builtin.file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0750"
  loop: [bin, log]
